version: '3.9'
services:
  app:
    build:
      dockerfile: docker/Dockerfile
      context: .
    volumes:
    - './:/app'
    entrypoint: 'vendor/bin/ecs --config=php71.php check sample.php'
#    entrypoint: 'vendor/bin/ecs show --config=php71.php'